# Generated by Django 5.0.2 on 2024-02-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='debts/', verbose_name='Файл Excel')),
                ('mailing_now', models.BooleanField(default=False, verbose_name='Сделать рассылку сейчас')),
            ],
            options={
                'verbose_name': 'Долги',
                'verbose_name_plural': 'Долги',
            },
        ),
    ]
