# Generated by Django 5.0.2 on 2024-02-08 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='УНП')),
                ('fio', models.CharField(max_length=256, unique=True, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('has_notifications', models.BooleanField(default=True, verbose_name='Уведомления')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, unique=True, verbose_name='Адрес')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='accounts.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, unique=True, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('has_notifications', models.BooleanField(default=True, verbose_name='Уведомления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='accounts.owner', verbose_name='Владелец')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='accounts.point', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
            },
        ),
    ]
