# Generated by Django 5.0.2 on 2024-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='employee',
            name='username',
            field=models.CharField(default='nick', max_length=64, unique=True, verbose_name='Юзернейм в Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='emp', max_length=64, unique=True, verbose_name='Юзернейм в Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='has_notifications',
            field=models.BooleanField(default=True, verbose_name='Включить ведомления'),
        ),
    ]
