# Generated by Django 5.0.2 on 2024-02-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_employee_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='tg_id',
            field=models.CharField(default='123', max_length=64, unique=True, verbose_name='ID в Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='tg_id',
            field=models.CharField(default='1234', max_length=64, unique=True, verbose_name='ID в Telegram'),
            preserve_default=False,
        ),
    ]
