# Generated by Django 5.0.2 on 2024-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_username_remove_owner_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unp', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='УНП')),
                ('fio', models.CharField(max_length=256, unique=True, verbose_name='ФИО')),
                ('tg_id', models.CharField(max_length=64, unique=True, verbose_name='ID в Telegram')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
