# Generated by Django 5.0.2 on 2024-02-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
