# Generated by Django 5.0.2 on 2024-02-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Подтвердить регистрацию'),
        ),
    ]
