# Generated by Django 5.0.2 on 2024-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='Разрешить самовывоз'),
        ),
    ]
