# Generated by Django 5.0.2 on 2024-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_owner_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='has_notifications',
            field=models.BooleanField(default=True, verbose_name='Включить уведомления'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='has_notifications',
            field=models.BooleanField(default=True, verbose_name='Включить уведомления'),
        ),
    ]
