# Generated by Django 5.0.2 on 2024-02-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_point_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='tg_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID в Telegram'),
        ),
    ]
