# Generated by Django 5.0.2 on 2024-03-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_owner_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fio',
            field=models.CharField(max_length=256, unique=True, verbose_name='Наименование'),
        ),
    ]
