# Generated by Django 5.0.2 on 2024-03-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_owner_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='reduced_limit',
            field=models.BooleanField(default=False, verbose_name='Понизить лимит в заказе до 10 шт.'),
        ),
    ]
