# Generated by Django 5.0.2 on 2024-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_owner_reduced_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='reg_pass',
            field=models.CharField(default='thebuter', max_length=32, verbose_name='Пароль для регситрации'),
        ),
    ]
