# Generated by Django 5.0.2 on 2024-02-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип продукции',
                'verbose_name_plural': 'Типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='orders.producttype', verbose_name='Тип продукции')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='accounts.owner', verbose_name='Владелец')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='orders.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Специальная цена',
                'verbose_name_plural': 'Специальные цены',
            },
        ),
    ]
