# Generated by Django 5.0.2 on 2024-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
    ]
