# Generated by Django 5.0.2 on 2024-02-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_owner_pickup'),
        ('orders', '0004_alter_order_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.point', verbose_name='Точка'),
        ),
    ]
