# Generated by Django 5.0.2 on 2024-02-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Создан'), ('AC', 'Принят'), ('CO', 'Завершен')], default='CR', max_length=32, verbose_name='Статус'),
        ),
    ]
