# Generated by Django 5.0.2 on 2024-02-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='excel_code',
            field=models.CharField(default=1, max_length=32, verbose_name='Код товара для Excel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='excel_name',
            field=models.CharField(default=1, max_length=32, verbose_name='Название для Excel'),
            preserve_default=False,
        ),
    ]
