# Generated by Django 5.0.2 on 2024-02-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_owner_pickup'),
        ('orders', '0010_product_excel_code_product_excel_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialprice',
            unique_together={('owner', 'product')},
        ),
    ]
