# Generated by Django 5.0.2 on 2024-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='excel_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='Код товара для Excel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='excel_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название для Excel'),
        ),
    ]
