# Generated by Django 5.0.2 on 2024-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_product_excel_code_alter_product_excel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукция'},
        ),
    ]
